name: peminjam_perpustakaan_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  dio: 5.4.0
  pretty_dio_logger: 1.3.1
  curved_navigation_bar: ^1.0.3
  another_carousel_pro: ^1.0.0
  get_storage: ^2.1.1
  intl: 0.19.0
  flutter: 
    sdk: flutter
  flutter_image_slideshow: ^0.1.6
  hexcolor: ^3.0.1
  google_fonts: 6.1.0
  cached_network_image: ^3.3.1
  flutter_rating_bar: ^4.0.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  flutter_svg: ^2.0.4
  flutter_font_icons: ^2.2.7


flutter: 
  uses-material-design: true
  assets:
    - assets/
    - assets/images/login2.png
    - assets/images/loginn.png
    - assets/images/one_piece.jpg
    - assets/images/naruto.jpg
    - assets/images/black_clover.jpg
    - assets/




